[pytest]
testpaths = tests
python_files = test_*.py
addopts = -p no:cacheprovider -p no:tmpdir
norecursedirs = .* _* data models logs scratch node_modules dist app .pytest_temp
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
